### PR TITLE
fix lose meta info when nodes topology change

### PR DESCRIPTION
**Pull request by xinz**

### CODE REVIEW

**Comment by xinz** [comment]
Resolve the conflict, and add the corresponding testing, please review and advise.

**Comment by bitwalker** [comment]
Some PRs were just merged, I'd like to get to this one, but looks like there are still some conflicts, can you resolve those? I'll try to get this merged ASAP once that's complete.

**Comment by xinz** [comment]
@bitwalker , resolved, please review and go ahead : )

**Comment by xinz** [comment]
@bitwalker , resolved and amend a missing, please review and go ahead if possible : )

**Comment by xinz** [comment]
Update: Resolve conflict base on the latest merged PRs

**Comment by slashdotdash** [comment]
Thanks for the pull request @xinz, sorry it took so long to merge your changes in.

**Pull request merged**
