### PR TITLE
Do not update tracker clock with registry entry clocks

### PR DESCRIPTION
**Pull request by tschmittni**
This is a follow up of https://github.com/bitwalker/swarm/pull/85

I forgot to change the handle_topology_change method which is
as far as I can tell also the root cause for
https://github.com/bitwalker/swarm/issues/106

### CODE REVIEW

**Comment by tschmittni** [comment]
I managed to reproduce https://github.com/bitwalker/swarm/issues/106 and this is happening because the clock gets forked on every anti-entropy sync. I removed the fork and added some more debug output when clock-forks are happening which should only be when a new node joins a cluster.

**Comment by arjan** [comment]
This is great! Do you think the situation you describe could be made reproducible in a testcase?

**Comment by tschmittni** [comment]
Added a test case

**Comment by beardedeagle** [comment]
This looks good so far, as I've been able to duplicate #106 myself I am going to pull this down and give it a spin.

**Comment by picaoao** [comment]
Tests are failing ... Any news on this ? This seems like a pretty critical and important fix !

**Comment by tschmittni** [comment]
Tests have been failing on the master branch before. Did this change cause any new failures?

**Pull request merged**
