### PR TITLE
Retry node up when `:swarm` fails to start

### PR DESCRIPTION
**Pull request by slashdotdash**
This pull request adds a retry mechanism to allow a newly joined node time to start the `:swarm` application. 

When testing an application that uses Swarm, I noticed the `nodeup` event was logging a warning when a node joined an already formed and running cluster. This was due to an error when calling `:application.ensure_all_started(:swarm)` on the starting node. The exception prevented the network topology change function call from occurring on the existing nodes.

Here's the log output before:

```
[warn] [swarm on node3@127.0.0.1] [tracker:nodeup] nodeup for node1@127.0.0.1 was ignored because swarm failed to start: {:error, {:swarm, {'no such file or directory', 'swarm.app'}}}
```

Afterwards the retry provides enough time for the node to start Swarm:

```
[warn] [swarm on node3@127.0.0.1] [tracker:nodeup] nodeup for node1@127.0.0.1 was ignored because swarm failed to start: {:error, {:swarm, {'no such file or directory', 'swarm.app'}}}, will retry in 1000ms..
[info] [swarm on node3@127.0.0.1] [tracker:nodeup] nodeup node1@127.0.0.1
[debug] [swarm on node3@127.0.0.1] [tracker:handle_topology_change] topology change (nodeup for node1@127.0.0.1)
[info] [swarm on node3@127.0.0.1] [tracker:handle_topology_change] topology change complete
```

Note I'm configuring the `:kernel` application and using `sync_nodes_optional` to define the available nodes so that a cluster is formed during node startup.

### CODE REVIEW

**Comment by bitwalker** [comment]
We should make sure that the retry is limited - if a node in the cluster starts but does not run swarm for some reason, this will end up recursing indefinitely. There are other ways to deal with that case, but I think it's reasonable to impose a retry limit of 3-5 attempts, at which point we bail. Thoughts?

**Comment by slashdotdash** [comment]
Yes, it's sensible to add a retry limit. I will make the change. 

I toyed with the idea of sending a delayed message to the Tracker process, using Process.send_after,  rather than blocking it with a sleep. What are your thoughts on that approach?

**Comment by slashdotdash** [comment]
@bitwalker I've pushed a commit to limit retries. The tracker process is now restricted to ten attempts, with a one second interval between each.

**Comment by bitwalker** [comment]
I have a couple of style changes I'd like to make, but I'll just merge this as-is and fix it directly to avoid making you wait. In case you have any future PRs in mind, I always avoid single-piping like `function(arg) |> other_fun`. In such cases, I prefer `other_fun(function(arg))` or `arg |> function() |> other_fun()` (and typically multi-line for such pipes).

Anyway, thanks for the excellent work!

**Pull request merged**
